name = "nwita-ai-linkedin-company-info"
compatibility_date = "2025-03-28"
main = "linkedin_company.js"
account_id = "46827c91abf2fd46f0c180ba88207593"
workers_dev = true

[triggers]
crons = []

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "KV_API_KEYS"
id = "61039c5a8d514a25b5df8a3da3845285"

[[kv_namespaces]]
binding = "KV_PROXY"
id = "86af15cd5a96445e921618842e38abd8"
